"""empty message

Revision ID: 554afcdabefe
Revises: 1b3472d30676
Create Date: 2019-11-21 22:46:51.119392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554afcdabefe'
down_revision = '1b3472d30676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('size', sa.Numeric(), nullable=True),
    sa.Column('alcohol_content', sa.Numeric(), nullable=True),
    sa.Column('nutritional_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_ID')
    )
    op.create_table('stock',
    sa.Column('warehouse_ID', sa.Integer(), nullable=False),
    sa.Column('product_ID', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_ID')
    )
    op.create_table('warehouse',
    sa.Column('warehouse_ID', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_ID')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('order',
    sa.Column('order_ID', sa.Integer(), nullable=False),
    sa.Column('customer_ID', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['customer.customer_ID'], ),
    sa.PrimaryKeyConstraint('order_ID')
    )
    op.create_table('order_items',
    sa.Column('order_ID', sa.Integer(), nullable=False),
    sa.Column('product_ID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_ID'], ['order.order_ID'], ),
    sa.ForeignKeyConstraint(['product_ID'], ['product.product_ID'], ),
    sa.PrimaryKeyConstraint('order_ID', 'product_ID')
    )
    op.create_table('shipping_to',
    sa.Column('order_ID', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_ID'], ['order.order_ID'], ),
    sa.ForeignKeyConstraint(['street_address'], ['product.product_ID'], ),
    sa.PrimaryKeyConstraint('order_ID', 'street_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_to')
    op.drop_table('order_items')
    op.drop_table('order')
    op.drop_table('staff')
    op.drop_table('warehouse')
    op.drop_table('stock')
    op.drop_table('product')
    # ### end Alembic commands ###
