"""empty message

Revision ID: 94a0e20935c5
Revises: a30e2badd814
Create Date: 2019-11-21 16:55:05.349293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a0e20935c5'
down_revision = 'a30e2badd814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('customer',
    sa.Column('customer_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('customer_ID')
    )
    op.drop_table('Customer')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_user_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='Users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Customer',
    sa.Column('customer_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['Users.user_id'], name='Customer_customer_ID_fkey'),
    sa.PrimaryKeyConstraint('customer_ID', name='Customer_pkey')
    )
    op.drop_table('customer')
    op.drop_table('users')
    # ### end Alembic commands ###
