"""empty message

Revision ID: a28927b53269
Revises: 17607f8319e1
Create Date: 2019-11-16 16:02:41.881149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28927b53269'
down_revision = '17607f8319e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'age')
    # ### end Alembic commands ###
